//! The Go summary script, embedded so there is no separate file to locate at
//! runtime.
//!
//! WitDiff writes this beside a copy of the target file and runs it with
//! `go run` (ADR-0017). Go's parser lives in the standard library, so no
//! dependency is needed on either side.

/// The script's format version.
pub const SUMMARY_FORMAT: u32 = 1;

/// Emit a normalized structural summary of one Go test file as JSON.
pub const SUMMARY_SCRIPT: &str = concat!(
    "// Summary script for Go test files. Run with `go run` from a temporary\n",
    "// directory containing only this file and the target (ADR-0017).\n",
    "package main\n",
    "\n",
    "import (\n",
    "	\"encoding/json\"\n",
    "	\"fmt\"\n",
    "	\"go/ast\"\n",
    "	\"go/parser\"\n",
    "	\"go/token\"\n",
    "	\"os\"\n",
    "	\"strings\"\n",
    ")\n",
    "\n",
    "// normalize renders an expression to a stable, formatting-insensitive form.\n",
    "// Deliberately not go/printer: this form is ours and both sides are versioned\n",
    "// together, so a toolchain change cannot alter the comparison.\n",
    "func normalize(e ast.Expr) string {\n",
    "	switch n := e.(type) {\n",
    "	case *ast.BasicLit:\n",
    "		return n.Value\n",
    "	case *ast.Ident:\n",
    "		return n.Name\n",
    "	case *ast.SelectorExpr:\n",
    "		return normalize(n.X) + \".\" + n.Sel.Name\n",
    "	case *ast.CallExpr:\n",
    "		parts := []string{}\n",
    "		for _, a := range n.Args {\n",
    "			parts = append(parts, normalize(a))\n",
    "		}\n",
    "		return normalize(n.Fun) + \"(\" + strings.Join(parts, \", \") + \")\"\n",
    "	case *ast.BinaryExpr:\n",
    "		return normalize(n.X) + \" \" + n.Op.String() + \" \" + normalize(n.Y)\n",
    "	case *ast.UnaryExpr:\n",
    "		return n.Op.String() + normalize(n.X)\n",
    "	case *ast.ParenExpr:\n",
    "		return normalize(n.X)\n",
    "	case *ast.IndexExpr:\n",
    "		return normalize(n.X) + \"[\" + normalize(n.Index) + \"]\"\n",
    "	case *ast.CompositeLit:\n",
    "		parts := []string{}\n",
    "		for _, el := range n.Elts {\n",
    "			parts = append(parts, normalize(el))\n",
    "		}\n",
    "		return \"{\" + strings.Join(parts, \", \") + \"}\"\n",
    "	case *ast.StarExpr:\n",
    "		return \"*\" + normalize(n.X)\n",
    "	case *ast.KeyValueExpr:\n",
    "		return normalize(n.Key) + \": \" + normalize(n.Value)\n",
    "	case *ast.TypeAssertExpr:\n",
    "		return normalize(n.X) + \".(type)\"\n",
    "	case *ast.SliceExpr:\n",
    "		return normalize(n.X) + \"[:]\"\n",
    "	}\n",
    "	return fmt.Sprintf(\"%T\", e)\n",
    "}\n",
    "\n",
    "type assertion struct {\n",
    "	Line int    `json:\"line\"`\n",
    "	Test string `json:\"test\"`\n",
    "}\n",
    "\n",
    "type function struct {\n",
    "	Name       string      `json:\"name\"`\n",
    "	Line       int         `json:\"line\"`\n",
    "	Assertions []assertion `json:\"assertions\"`\n",
    "	Skipped    bool        `json:\"skipped\"`\n",
    "	Empty      bool        `json:\"body_is_empty\"`\n",
    "}\n",
    "\n",
    "// failureCall reports whether a call is a test failure report, and returns the\n",
    "// expression that was checked when one can be identified.\n",
    "//\n",
    "// Go has no assertion keyword: a test fails by calling t.Error, t.Errorf,\n",
    "// t.Fatal, t.Fatalf, or t.Fail. The meaningful part is the *condition* that\n",
    "// guarded the call, so the enclosing `if` is what gets normalized.\n",
    "func failureCall(call *ast.CallExpr) bool {\n",
    "	sel, ok := call.Fun.(*ast.SelectorExpr)\n",
    "	if !ok {\n",
    "		return false\n",
    "	}\n",
    "	switch sel.Sel.Name {\n",
    "	case \"Error\", \"Errorf\", \"Fatal\", \"Fatalf\", \"Fail\", \"FailNow\":\n",
    "		return true\n",
    "	}\n",
    "	return false\n",
    "}\n",
    "\n",
    "// guardOf walks up from a failure call to find the condition guarding it.\n",
    "// Go's idiom is `if got != want { t.Errorf(...) }`, so the `if` condition is\n",
    "// the assertion.\n",
    "func guardOf(root ast.Node, target *ast.CallExpr) ast.Expr {\n",
    "	var found ast.Expr\n",
    "	ast.Inspect(root, func(n ast.Node) bool {\n",
    "		ifStmt, ok := n.(*ast.IfStmt)\n",
    "		if !ok {\n",
    "			return true\n",
    "		}\n",
    "		ast.Inspect(ifStmt.Body, func(inner ast.Node) bool {\n",
    "			if inner == target {\n",
    "				found = ifStmt.Cond\n",
    "				return false\n",
    "			}\n",
    "			return true\n",
    "		})\n",
    "		return found == nil\n",
    "	})\n",
    "	return found\n",
    "}\n",
    "\n",
    "func main() {\n",
    "	if len(os.Args) != 2 {\n",
    "		fmt.Fprintln(os.Stderr, \"usage: summarize <path>\")\n",
    "		os.Exit(2)\n",
    "	}\n",
    "	fset := token.NewFileSet()\n",
    "	file, err := parser.ParseFile(fset, os.Args[1], nil, parser.ParseComments)\n",
    "	if err != nil {\n",
    "		json.NewEncoder(os.Stdout).Encode(map[string]any{\"format\": 1, \"error\": err.Error()})\n",
    "		return\n",
    "	}\n",
    "\n",
    "	functions := []function{}\n",
    "	for _, decl := range file.Decls {\n",
    "		fn, ok := decl.(*ast.FuncDecl)\n",
    "		if !ok || fn.Body == nil {\n",
    "			continue\n",
    "		}\n",
    "		// Go collects any function named TestXxx or BenchmarkXxx.\n",
    "		if !strings.HasPrefix(fn.Name.Name, \"Test\") && !strings.HasPrefix(fn.Name.Name, \"Benchmark\") {\n",
    "			continue\n",
    "		}\n",
    "\n",
    "		assertions := []assertion{}\n",
    "		ast.Inspect(fn.Body, func(n ast.Node) bool {\n",
    "			call, ok := n.(*ast.CallExpr)\n",
    "			if !ok || !failureCall(call) {\n",
    "				return true\n",
    "			}\n",
    "			test := \"t.Fail()\"\n",
    "			if guard := guardOf(fn.Body, call); guard != nil {\n",
    "				test = normalize(guard)\n",
    "			} else if len(call.Args) > 0 {\n",
    "				test = \"t.Error(\" + normalize(call.Args[0]) + \")\"\n",
    "			}\n",
    "			assertions = append(assertions, assertion{\n",
    "				Line: fset.Position(call.Pos()).Line,\n",
    "				Test: test,\n",
    "			})\n",
    "			return true\n",
    "		})\n",
    "\n",
    "		// A test that calls t.Skip no longer checks anything, which is the Go\n",
    "		// equivalent of Rust's #[ignore] and Python's pytest.mark.skip.\n",
    "		skipped := false\n",
    "		ast.Inspect(fn.Body, func(n ast.Node) bool {\n",
    "			call, ok := n.(*ast.CallExpr)\n",
    "			if !ok {\n",
    "				return true\n",
    "			}\n",
    "			if sel, ok := call.Fun.(*ast.SelectorExpr); ok {\n",
    "				if sel.Sel.Name == \"Skip\" || sel.Sel.Name == \"Skipf\" || sel.Sel.Name == \"SkipNow\" {\n",
    "					skipped = true\n",
    "				}\n",
    "			}\n",
    "			return true\n",
    "		})\n",
    "\n",
    "		empty := len(fn.Body.List) == 0\n",
    "		functions = append(functions, function{\n",
    "			Name:       fn.Name.Name,\n",
    "			Line:       fset.Position(fn.Pos()).Line,\n",
    "			Assertions: assertions,\n",
    "			Skipped:    skipped,\n",
    "			Empty:      empty,\n",
    "		})\n",
    "	}\n",
    "	json.NewEncoder(os.Stdout).Encode(map[string]any{\"format\": 1, \"functions\": functions})\n",
    "}\n",
    "\n",
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_script_has_the_expected_shape() {
        assert!(SUMMARY_SCRIPT.contains("go/parser"));
        assert!(SUMMARY_SCRIPT.contains("go/ast"));
        assert!(SUMMARY_SCRIPT.contains("func main()"));
    }

    /// Go has no assertion keyword, so the guard condition is the assertion.
    /// If that logic went missing the analyzer would compare error messages.
    #[test]
    fn the_script_looks_for_guarding_conditions() {
        assert!(SUMMARY_SCRIPT.contains("func guardOf"));
        assert!(SUMMARY_SCRIPT.contains("*ast.IfStmt"));
    }

    #[test]
    fn the_script_detects_skips() {
        assert!(SUMMARY_SCRIPT.contains(r#""Skip""#));
    }
}
