//! The JavaScript and TypeScript summary tool, embedded so there is no
//! separate file to locate at runtime.
//!
//! Run as `node tool.js <path> <project-dir>` (ADR-0021). The parser is
//! required from the **project**, never bundled: WitDiff must analyze with the
//! parser the project tests with, and a version difference would appear as
//! spurious findings.
//!
//! The project directory is an argument rather than the working directory
//! because Node resolves `require` relative to the script's own directory, not
//! the working directory. Verified directly.

/// The tool's format version.
pub const SUMMARY_FORMAT: u32 = 1;

/// Emit a normalized structural summary of one JavaScript or TypeScript test
/// file as JSON.
pub const SUMMARY_SCRIPT: &str = concat!(
    "// Summary tool for JavaScript and TypeScript test files (ADR-0021).\n",
    "//\n",
    "// Run as: node js_summarizer.js <path>\n",
    "//\n",
    "// The parser is required from the *project*, never bundled: WitDiff must use\n",
    "// the parser the project tests with, or a version difference would show up as\n",
    "// spurious findings.\n",
    "const fs = require(\"fs\");\n",
    "\n",
    "// Parsers are tried in order; all produce an ESTree-compatible tree, so one\n",
    "// traversal serves them all.\n",
    "const PARSERS = [\"@babel/parser\", \"acorn\", \"typescript\"];\n",
    "\n",
    "// Node resolves `require` relative to the SCRIPT's directory, not the working\n",
    "// directory, so a tool run from a temp directory cannot see the project's\n",
    "// node_modules no matter what cwd it is given. Verified directly: running the\n",
    "// tool from /private/tmp/jsgap with cwd set there still failed to resolve acorn,\n",
    "// because the script lived in /var/folders/....\n",
    "//\n",
    "// So the project directory is passed explicitly and each candidate is required\n",
    "// by absolute path.\n",
    "function loadParser(projectDir) {\n",
    "  for (const name of PARSERS) {\n",
    "    try {\n",
    "      const path = require(\"path\");\n",
    "      const resolved = require.resolve(path.join(projectDir, \"node_modules\", name));\n",
    "      return { name, module: require(resolved) };\n",
    "    } catch (error) {\n",
    "      // Not installed in this project; try the next.\n",
    "    }\n",
    "  }\n",
    "  return null;\n",
    "}\n",
    "\n",
    "function parseSource(source, parser) {\n",
    "  if (parser.name === \"@babel/parser\") {\n",
    "    return parser.module.parse(source, {\n",
    "      sourceType: \"unambiguous\",\n",
    "      plugins: [\"typescript\", \"jsx\", \"classProperties\"],\n",
    "      errorRecovery: true,\n",
    "    });\n",
    "  }\n",
    "  if (parser.name === \"typescript\") {\n",
    "    const file = parser.module.createSourceFile(\n",
    "      \"input.ts\",\n",
    "      source,\n",
    "      parser.module.ScriptTarget.Latest,\n",
    "      true,\n",
    "      parser.module.ScriptKind.TSX\n",
    "    );\n",
    "    const diagnostics = file.parseDiagnostics || [];\n",
    "    if (diagnostics.length > 0) {\n",
    "      return { error: \"typescript_parse_error\" };\n",
    "    }\n",
    "    return file;\n",
    "  }\n",
    "  return parser.module.parse(source, {\n",
    "    ecmaVersion: \"latest\",\n",
    "    sourceType: \"unambiguous\",\n",
    "    locations: true,\n",
    "    allowReturnOutsideFunction: true,\n",
    "  });\n",
    "}\n",
    "\n",
    "// Render an expression to a stable, formatting-insensitive string. Ours and\n",
    "// versioned on both sides, so a parser change cannot alter the comparison.\n",
    "function normalize(node) {\n",
    "  if (!node) return \"\";\n",
    "  switch (node.type) {\n",
    "    case \"Identifier\":\n",
    "    case \"PrivateName\":\n",
    "      return node.name;\n",
    "    case \"NumericLiteral\":\n",
    "    case \"StringLiteral\":\n",
    "    case \"BooleanLiteral\":\n",
    "      return JSON.stringify(node.value);\n",
    "    case \"NullLiteral\":\n",
    "      return \"null\";\n",
    "    case \"MemberExpression\":\n",
    "      return (\n",
    "        normalize(node.object) +\n",
    "        (node.computed ? \"[...]\" : \".\" + normalize(node.property))\n",
    "      );\n",
    "    case \"CallExpression\":\n",
    "    case \"OptionalCallExpression\": {\n",
    "      const args = (node.arguments || [])\n",
    "        .filter((a) => a.type !== \"SpreadElement\")\n",
    "        .map(normalize);\n",
    "      return normalize(node.callee) + \"(\" + args.join(\", \") + \")\";\n",
    "    }\n",
    "    case \"NewExpression\":\n",
    "      return \"new \" + normalize(node.callee);\n",
    "    case \"BinaryExpression\":\n",
    "    case \"LogicalExpression\": {\n",
    "      const op = node.operator === \"===\" ? \"==\" : node.operator;\n",
    "      return normalize(node.left) + \" \" + op + \" \" + normalize(node.right);\n",
    "    }\n",
    "    case \"UnaryExpression\":\n",
    "      return node.operator + normalize(node.argument);\n",
    "    case \"ConditionalExpression\":\n",
    "      return (\n",
    "        normalize(node.test) +\n",
    "        \" ? \" +\n",
    "        normalize(node.consequent) +\n",
    "        \" : \" +\n",
    "        normalize(node.alternate)\n",
    "      );\n",
    "    case \"ArrayExpression\":\n",
    "      return \"[\" + (node.elements || []).map(normalize).join(\", \") + \"]\";\n",
    "    case \"ObjectExpression\":\n",
    "      return (\n",
    "        \"{\" +\n",
    "        (node.properties || [])\n",
    "          .map((p) => normalize(p.key) + \": \" + normalize(p.value))\n",
    "          .join(\", \") +\n",
    "        \"}\"\n",
    "      );\n",
    "    case \"TemplateLiteral\": {\n",
    "      const exprs = (node.expressions || []).map(normalize);\n",
    "      return \"`\" + (node.quasis || []).map((q) => q.value.raw).join(\"${\") + (exprs.length ? exprs.join(\", \") : \"\") + \"}`\";\n",
    "    }\n",
    "    case \"AwaitExpression\":\n",
    "      return \"await \" + normalize(node.argument);\n",
    "    case \"TSAsExpression\":\n",
    "    case \"TSSatisfiesExpression\":\n",
    "      return normalize(node.expression);\n",
    "    case \"TSNonNullExpression\":\n",
    "      return normalize(node.expression);\n",
    "    default:\n",
    "      // Named rather than guessed, so an unhandled form participates in\n",
    "      // comparison without pretending to be understood.\n",
    "      return node.type;\n",
    "  }\n",
    "}\n",
    "\n",
    "// Assertion helpers, and the matcher each implies.\n",
    "const EQUALITY_MATCHERS = new Set([\"toBe\", \"toEqual\", \"toStrictEqual\"]);\n",
    "const NEGATED = new Set([\"not\"]);\n",
    "const ASSERT_METHODS = new Set([\n",
    "  \"expect\",\n",
    "  \"assert\",\n",
    "  \"toBeTruthy\",\n",
    "  \"toBeFalsy\",\n",
    "  \"toBeDefined\",\n",
    "  \"toBeUndefined\",\n",
    "  \"toBeNull\",\n",
    "  \"toThrow\",\n",
    "  \"toContain\",\n",
    "  \"toMatch\",\n",
    "]);\n",
    "\n",
    "// Jest/Vitest: `expect(x).toBe(y)` is an ESTree CallExpression whose callee is a\n",
    "// MemberExpression chain `expect(x).toBe`. Jest's `assert(x, y)` is a plain call.\n",
    "function assertionFromCall(node) {\n",
    "  if (node.type !== \"CallExpression\") return null;\n",
    "  const callee = node.callee;\n",
    "  if (callee.type !== \"MemberExpression\") {\n",
    "    // `assert(cond, message)` is a whole call.\n",
    "    if (\n",
    "      callee.type === \"Identifier\" &&\n",
    "      /^(assert|assertTrue|assertFalse|assertEqual|assertStrictEqual|assertNotEqual|assertDeepEqual|assertThrows)$/.test(\n",
    "        callee.name\n",
    "      )\n",
    "    ) {\n",
    "      const args = node.arguments || [];\n",
    "      if (args.length === 0) return null;\n",
    "      const subject = normalize(args[0]);\n",
    "      if (args.length >= 2 && /^assert(Not)?(Strict)?(Deep)?Equal$/.test(callee.name)) {\n",
    "        const negated = callee.name.includes(\"Not\") ? \" NotEq \" : \" Eq \";\n",
    "        return subject + negated + normalize(args[1]);\n",
    "      }\n",
    "      return subject;\n",
    "    }\n",
    "    return null;\n",
    "  }\n",
    "  // `expect(x)` must be at the base of the member chain. For `.not` the shape\n",
    "  // is one level deeper — expect(x).not.toBe(y) — so the base is unwrapped\n",
    "  // before checking. Reading it without unwrapping returned null for every\n",
    "  // negated expectation.\n",
    "  let object = callee.object;\n",
    "  let negated = false;\n",
    "  if (object && object.type === \"CallExpression\" && object.callee &&\n",
    "      object.callee.type === \"MemberExpression\") {\n",
    "    negated = true;\n",
    "    object = object.callee.object;\n",
    "  }\n",
    "  if (!object || object.type !== \"CallExpression\") return null;\n",
    "  const inner = object.callee;\n",
    "  if (!inner || inner.type !== \"Identifier\") return null;\n",
    "  const helper = inner.name;\n",
    "  if (helper !== \"expect\" && helper !== \"should\") return null;\n",
    "\n",
    "  const args = object.arguments || [];\n",
    "  if (args.length === 0) return null;\n",
    "  const subject = normalize(args[0]);\n",
    "\n",
    "  // `.not.toBe(y)` nests one level deeper: expect(x).not is the inner member,\n",
    "  // and `.toBe` is the outer one. Both are unwrapped here, and the matcher is\n",
    "  // taken from whichever level is not `not`.\n",
    "  let matcher = callee.property;\n",
    "  if (negated) {\n",
    "    const outer = node.callee;\n",
    "    if (!outer || outer.type !== \"MemberExpression\") return subject;\n",
    "    matcher = outer.property;\n",
    "  }\n",
    "  const matcherName = matcher && matcher.type === \"Identifier\" ? matcher.name : \"\";\n",
    "  // The expectation sits on whichever call carries the matcher: the outer node\n",
    "  // normally, and the inner node for the doubly-nested `.not` shape.\n",
    "  let values = (node.arguments || []).map(normalize);\n",
    "  if (negated && values.length === 0 && callee.object && callee.object.arguments) {\n",
    "    values = callee.object.arguments.map(normalize);\n",
    "  }\n",
    "  if (EQUALITY_MATCHERS.has(matcherName) && values.length > 0) {\n",
    "    return subject + (negated ? \" NotEq \" : \" Eq \") + values[0];\n",
    "  }\n",
    "  // Every other matcher constrains the subject alone.\n",
    "  return subject;\n",
    "}\n",
    "\n",
    "// Walk every node in the tree.\n",
    "function walk(node, visit) {\n",
    "  if (!node || typeof node !== \"object\") return;\n",
    "  if (Array.isArray(node)) {\n",
    "    for (const child of node) walk(child, visit);\n",
    "    return;\n",
    "  }\n",
    "  if (typeof node.type === \"string\") visit(node);\n",
    "  for (const key of Object.keys(node)) {\n",
    "    if (key === \"loc\" || key === \"leadingComments\" || key === \"trailingComments\") continue;\n",
    "    walk(node[key], visit);\n",
    "  }\n",
    "}\n",
    "\n",
    "// A test function or arrow assigned to a `test`-like call.\n",
    "function isTestName(name) {\n",
    "  return /^(test|it|specify)(\\.|$)/.test(name) || /^Test|^Spec/.test(name);\n",
    "}\n",
    "\n",
    "function summarize(file, parser) {\n",
    "  const source = fs.readFileSync(file, \"utf-8\");\n",
    "  const tree = parseSource(source, parser);\n",
    "  if (!tree) return { format: 1, error: \"could not parse\" };\n",
    "  if (tree.error) return { format: 1, error: tree.error };\n",
    "\n",
    "  const functions = [];\n",
    "\n",
    "  walk(tree, (node) => {\n",
    "    // A test is a CallExpression whose callee is `test`/`it`/`specify`.\n",
    "    if (node.type === \"CallExpression\" && node.callee && node.callee.type === \"Identifier\") {\n",
    "      const helper = node.callee.name;\n",
    "      if (isTestName(helper)) {\n",
    "        const label = (node.arguments || [])\n",
    "          .filter((a) => a.type === \"Literal\" || a.type === \"StringLiteral\")\n",
    "          .map((a) => String(a.value))\n",
    "          .join(\" \");\n",
    "        const name = label ? `${helper}: ${label}` : `${helper}@${node.loc ? node.loc.start.line : 0}`;\n",
    "        functions.push(collectBody(name, node.loc ? node.loc.start.line : 0, node));\n",
    "        return;\n",
    "      }\n",
    "    }\n",
    "    // A Minitest-style `function test_foo() {}` or `const test = () => {}`.\n",
    "    if (node.type === \"FunctionDeclaration\" && node.id && isTestName(node.id.name)) {\n",
    "      functions.push(collectBody(node.id.name, node.loc ? node.loc.start.line : 0, node));\n",
    "      return;\n",
    "    }\n",
    "    if (\n",
    "      node.type === \"VariableDeclarator\" &&\n",
    "      node.id &&\n",
    "      node.id.type === \"Identifier\" &&\n",
    "      isTestName(node.id.name) &&\n",
    "      node.init &&\n",
    "      (node.init.type === \"ArrowFunctionExpression\" || node.init.type === \"FunctionExpression\")\n",
    "    ) {\n",
    "      functions.push(collectBody(node.id.name, node.loc ? node.loc.start.line : 0, node.init));\n",
    "    }\n",
    "  });\n",
    "\n",
    "  return { format: 1, parser: parser.name, functions };\n",
    "}\n",
    "\n",
    "function collectBody(name, line, node) {\n",
    "  const assertions = [];\n",
    "  const guards = [];\n",
    "  const bindings = {};\n",
    "\n",
    "  walk(node, (child) => {\n",
    "    const found = assertionFromCall(child);\n",
    "    if (found !== null && found !== \"\") {\n",
    "      assertions.push({ line: child.loc ? child.loc.start.line : 0, test: found });\n",
    "    }\n",
    "    // A thrown assertion is a failure guard, not an expectation.\n",
    "    if (\n",
    "      child.type === \"IfStatement\" &&\n",
    "      child.consequent &&\n",
    "      child.consequent.type === \"BlockStatement\"\n",
    "    ) {\n",
    "      const throws = (child.consequent.body || []).some(\n",
    "        (s) =>\n",
    "          s.type === \"ThrowStatement\" ||\n",
    "          (s.type === \"ExpressionStatement\" &&\n",
    "            s.expression &&\n",
    "            s.expression.type === \"CallExpression\" &&\n",
    "            s.expression.callee &&\n",
    "            (s.expression.callee.name === \"fail\" ||\n",
    "              s.expression.callee.name === \"assert\"))\n",
    "      );\n",
    "      if (throws) guards.push(normalize(child.test));\n",
    "    }\n",
    "  });\n",
    "\n",
    "  return {\n",
    "    name,\n",
    "    line,\n",
    "    assertions,\n",
    "    skipped: false,\n",
    "    body_is_empty: false,\n",
    "    bindings,\n",
    "    guards,\n",
    "  };\n",
    "}\n",
    "\n",
    "function main() {\n",
    "  const file = process.argv[2];\n",
    "  const projectDir = process.argv[3] || process.cwd();\n",
    "  const parser = loadParser(projectDir);\n",
    "  if (!parser) {\n",
    "    process.stdout.write(\n",
    "      JSON.stringify({\n",
    "        format: 1,\n",
    "        error:\n",
    "          \"no JavaScript parser available; install one of @babel/parser, acorn or typescript as a project dependency\",\n",
    "      })\n",
    "    );\n",
    "    return;\n",
    "  }\n",
    "  try {\n",
    "    process.stdout.write(JSON.stringify(summarize(file, parser)));\n",
    "  } catch (error) {\n",
    "    process.stdout.write(\n",
    "      JSON.stringify({ format: 1, error: String(error && error.message ? error.message : error) })\n",
    "    );\n",
    "  }\n",
    "}\n",
    "\n",
    "main();\n",
    "\n",
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_tool_has_the_expected_shape() {
        assert!(SUMMARY_SCRIPT.contains("PARSERS"));
        assert!(SUMMARY_SCRIPT.contains("@babel/parser"));
        assert!(SUMMARY_SCRIPT.contains("acorn"));
        assert!(SUMMARY_SCRIPT.contains("typescript"));
    }

    /// The parser must be required from the project, never bundled, and its
    /// absence must be reported rather than worked around.
    #[test]
    fn a_missing_parser_is_reported() {
        assert!(SUMMARY_SCRIPT.contains("no JavaScript parser available"));
        assert!(
            !SUMMARY_SCRIPT.contains("require(\"acorn\")"),
            "the parser must be resolved dynamically, not hard-required"
        );
    }

    /// `.not` nests one level deeper than `.toBe`, and reading the matcher
    /// without unwrapping returned null for every negated expectation.
    #[test]
    fn the_tool_unwraps_the_expect_base() {
        assert!(SUMMARY_SCRIPT.contains("object = object.callee.object"));
    }

    /// Equality matchers normalize to the canonical subject-first form; every
    /// other matcher constrains the subject alone.
    #[test]
    fn the_tool_normalizes_equality_matchers() {
        assert!(SUMMARY_SCRIPT.contains("EQUALITY_MATCHERS"));
        assert!(SUMMARY_SCRIPT.contains(" NotEq "));
        assert!(SUMMARY_SCRIPT.contains(" Eq "));
    }
    /// Node resolves `require` relative to the *script's* directory, not the
    /// working directory, so a tool in a temp directory cannot see the
    /// project's node_modules however it is invoked. Verified directly. The
    /// project directory is therefore passed explicitly and each candidate is
    /// required by absolute path.
    #[test]
    fn the_tool_resolves_the_parser_by_absolute_path() {
        assert!(SUMMARY_SCRIPT.contains("node_modules"));
        assert!(SUMMARY_SCRIPT.contains("require.resolve"));
        assert!(SUMMARY_SCRIPT.contains("projectDir"));
    }
}
