//! The JavaScript and TypeScript summary tool, embedded so there is no
//! separate file to locate at runtime.
//!
//! Run as `node tool.js <path> <project-dir>` (ADR-0021). The parser is
//! required from the **project**, never bundled: WitDiff must analyze with the
//! parser the project tests with, and a version difference would appear as
//! spurious findings.
//!
//! The project directory is an argument rather than the working directory
//! because Node resolves `require` relative to the script's own directory, not
//! the working directory. Verified directly.

/// The tool's format version.
pub const SUMMARY_FORMAT: u32 = 1;

/// Emit a normalized structural summary of one JavaScript or TypeScript test
/// file as JSON.
pub const SUMMARY_SCRIPT: &str = concat!(
    "// Summary tool for JavaScript and TypeScript test files (ADR-0021).\n",
    "const fs = require(\"fs\");\n",
    "const path = require(\"path\");\n",
    "\n",
    "const PARSERS = [\"@babel/parser\", \"acorn\", \"typescript\"];\n",
    "\n",
    "// Resolve every parser the project actually has, in order.\n",
    "//\n",
    "// Not just the first one: the choice must depend on what the file *needs*, not\n",
    "// on what happens to be installed. A TypeScript project with acorn installed\n",
    "// would otherwise be handed to acorn, which cannot read a type annotation, and\n",
    "// the file would be reported as unparsable. Measured against a real acorn\n",
    "// before this was fixed: every `.ts` file came back \"Unexpected token\".\n",
    "function loadParsers(projectDir) {\n",
    "  const found = [];\n",
    "  for (const name of PARSERS) {\n",
    "    try {\n",
    "      const resolved = require.resolve(path.join(projectDir, \"node_modules\", name));\n",
    "      found.push({ name, module: require(resolved) });\n",
    "    } catch (error) {\n",
    "      // Not installed in this project; try the next.\n",
    "    }\n",
    "  }\n",
    "  return found;\n",
    "}\n",
    "\n",
    "function parseWith(source, parser, file) {\n",
    "  if (parser.name === \"@babel/parser\") {\n",
    "    return parser.module.parse(source, {\n",
    "      sourceType: \"unambiguous\",\n",
    "      plugins: [\"typescript\", \"jsx\", \"classProperties\"],\n",
    "      errorRecovery: true,\n",
    "    });\n",
    "  }\n",
    "  if (parser.name === \"typescript\") {\n",
    "    const ts = parser.module;\n",
    "    // `setParentNodes` is false on purpose: a parent back-pointer turns the\n",
    "    // tree into a cycle, and the traversal below has no visited-set, so it\n",
    "    // recursed until the stack overflowed. Measured: \"Maximum call stack size\n",
    "    // exceeded\" and zero functions found on a valid .ts file.\n",
    "    const sf = ts.createSourceFile(\n",
    "      file.endsWith(\".tsx\") ? \"input.tsx\" : \"input.ts\",\n",
    "      source,\n",
    "      ts.ScriptTarget.Latest,\n",
    "      false,\n",
    "      file.endsWith(\".tsx\") ? ts.ScriptKind.TSX : ts.ScriptKind.TS\n",
    "    );\n",
    "    const diagnostics = (sf.parseDiagnostics || []).concat(\n",
    "      sf.parseDiagnostics || []\n",
    "    );\n",
    "    if (diagnostics.length > 0) {\n",
    "      throw new Error(\"typescript_parse_error\");\n",
    "    }\n",
    "    annotateTypeScript(sf, ts);\n",
    "    return sf;\n",
    "  }\n",
    "  return parser.module.parse(source, {\n",
    "    ecmaVersion: \"latest\",\n",
    "    sourceType: \"unambiguous\",\n",
    "    locations: true,\n",
    "    allowReturnOutsideFunction: true,\n",
    "    // Jest and Vitest files routinely use top-level `await` inside hooks.\n",
    "    allowAwaitOutsideFunction: true,\n",
    "  });\n",
    "}\n",
    "\n",
    "// The TypeScript AST tags nodes with a numeric `kind`, not an ESTree `type`, so\n",
    "// the shared traversal below visited nothing and every `.ts` file analyzed as\n",
    "// zero tests. Map the kind name onto `type`, and reshape the handful of nodes\n",
    "// whose fields differ, so one traversal serves ESTree and TypeScript alike.\n",
    "const TS_RENAME = {\n",
    "  PropertyAccessExpression: \"MemberExpression\",\n",
    "  QualifiedName: \"MemberExpression\",\n",
    "  ObjectLiteralExpression: \"ObjectExpression\",\n",
    "  ArrayLiteralExpression: \"ArrayExpression\",\n",
    "  PropertyAssignment: \"Property\",\n",
    "  ShorthandPropertyAssignment: \"Property\",\n",
    "  SpreadAssignment: \"SpreadElement\",\n",
    "  PrefixUnaryExpression: \"UnaryExpression\",\n",
    "  PostfixUnaryExpression: \"UnaryExpression\",\n",
    "  AsExpression: \"TSAsExpression\",\n",
    "  SatisfiesExpression: \"TSSatisfiesExpression\",\n",
    "  TypeAssertionExpression: \"TSAsExpression\",\n",
    "  NonNullExpression: \"TSNonNullExpression\",\n",
    "  JsxElement: \"JSXElement\",\n",
    "  JsxSelfClosingElement: \"JSXElement\",\n",
    "  JsxFragment: \"JSXFragment\",\n",
    "  JsxExpression: \"JSXExpressionContainer\",\n",
    "};\n",
    "\n",
    "function operatorText(token, ts) {\n",
    "  if (token === undefined || token === null) return \"\";\n",
    "  if (typeof token === \"number\") {\n",
    "    // `ts.SyntaxKind` also carries `FirstAssignment..LastBinaryOperator`\n",
    "    // aliases, which is what makes this reliable across versions.\n",
    "    const alias = ts.tokenToString ? ts.tokenToString(token) : undefined;\n",
    "    return alias || \"\";\n",
    "  }\n",
    "  return String(token);\n",
    "}\n",
    "\n",
    "function annotateTypeScript(root, ts) {\n",
    "  const sourceFile = root;\n",
    "  const stack = [root];\n",
    "  while (stack.length) {\n",
    "    const node = stack.pop();\n",
    "    if (!node || typeof node !== \"object\") continue;\n",
    "    if (Array.isArray(node)) {\n",
    "      for (const child of node) stack.push(child);\n",
    "      continue;\n",
    "    }\n",
    "    if (typeof node.kind !== \"number\") continue;\n",
    "\n",
    "    // `ts.SyntaxKind[node.kind]` is unreliable for literals: the reverse\n",
    "    // mapping resolves every kind in FirstLiteralToken..LastLiteralToken to\n",
    "    // the *alias* name, so `2` came back as \"FirstLiteralToken\" and every\n",
    "    // numeric expectation normalized to that word. Measured: `toBe(2)` and\n",
    "    // `toBe(3)` rendered identically. The numeric enum members are used here.\n",
    "    const kind = node.kind;\n",
    "    let type;\n",
    "    if (kind === ts.SyntaxKind.TrueKeyword) type = \"BooleanLiteral\";\n",
    "    else if (kind === ts.SyntaxKind.FalseKeyword) type = \"BooleanLiteral\";\n",
    "    else if (kind === ts.SyntaxKind.NullKeyword) type = \"NullLiteral\";\n",
    "    else if (kind === ts.SyntaxKind.NumericLiteral) type = \"NumericLiteral\";\n",
    "    else if (kind === ts.SyntaxKind.BigIntLiteral) type = \"BigIntLiteral\";\n",
    "    else if (kind === ts.SyntaxKind.StringLiteral) type = \"StringLiteral\";\n",
    "    else if (kind === ts.SyntaxKind.RegularExpressionLiteral) {\n",
    "      type = \"RegularExpressionLiteral\";\n",
    "    } else if (\n",
    "      kind === ts.SyntaxKind.NoSubstitutionTemplateLiteral ||\n",
    "      kind === ts.SyntaxKind.TemplateHead ||\n",
    "      kind === ts.SyntaxKind.TemplateMiddle ||\n",
    "      kind === ts.SyntaxKind.TemplateTail\n",
    "    ) {\n",
    "      type = kind === ts.SyntaxKind.NoSubstitutionTemplateLiteral\n",
    "        ? \"NoSubstitutionTemplateLiteral\"\n",
    "        : \"TemplateLiteral\";\n",
    "    } else {\n",
    "      const kindName = ts.SyntaxKind[kind];\n",
    "      type = TS_RENAME[kindName] || kindName;\n",
    "    }\n",
    "\n",
    "    switch (kind) {\n",
    "      case ts.SyntaxKind.TrueKeyword:\n",
    "        node.value = true;\n",
    "        break;\n",
    "      case ts.SyntaxKind.FalseKeyword:\n",
    "        node.value = false;\n",
    "        break;\n",
    "      case ts.SyntaxKind.NullKeyword:\n",
    "        node.value = null;\n",
    "        break;\n",
    "      case ts.SyntaxKind.NumericLiteral:\n",
    "        // Unquoted: acorn's `Literal` carries a JSON number, and the two\n",
    "        // parsers must render the same expectation identically or every\n",
    "        // comparison between them is a false difference.\n",
    "        node.value = Number(node.text);\n",
    "        break;\n",
    "      case ts.SyntaxKind.BigIntLiteral:\n",
    "        node.value = node.text;\n",
    "        break;\n",
    "      case ts.SyntaxKind.StringLiteral:\n",
    "      case ts.SyntaxKind.NoSubstitutionTemplateLiteral:\n",
    "        node.value = unquote(node.text);\n",
    "        break;\n",
    "      case ts.SyntaxKind.RegularExpressionLiteral:\n",
    "        node.regex = { pattern: node.text };\n",
    "        break;\n",
    "      default:\n",
    "        break;\n",
    "    }\n",
    "\n",
    "    // Positions. Every finding names the line it was observed at, and a file\n",
    "    // analyzed with every line reported as 0 sends a reader to the wrong place.\n",
    "    if (typeof node.pos === \"number\" && typeof node.end === \"number\") {\n",
    "      const start = sourceFile.getLineAndCharacterOfPosition(node.pos);\n",
    "      node.loc = {\n",
    "        start: { line: start.line + 1 },\n",
    "        end: { line: start.line + 1 },\n",
    "      };\n",
    "    }\n",
    "\n",
    "    switch (type) {\n",
    "      case \"Identifier\":\n",
    "      case \"PrivateIdentifier\":\n",
    "        node.name = node.text !== undefined ? node.text : node.name;\n",
    "        break;\n",
    "      case \"MemberExpression\":\n",
    "        node.computed = Boolean(node.questionDotToken);\n",
    "        node.object = node.expression;\n",
    "        node.property = node.name;\n",
    "        break;\n",
    "      case \"CallExpression\":\n",
    "      case \"NewExpression\":\n",
    "        node.callee = node.expression;\n",
    "        break;\n",
    "      case \"Property\":\n",
    "        node.key = node.name;\n",
    "        node.value = node.initializer || node.objectLiteralElementInitializer;\n",
    "        break;\n",
    "      case \"UnaryExpression\":\n",
    "        node.argument = node.operand;\n",
    "        node.operator = operatorText(node.operator, ts);\n",
    "        break;\n",
    "      case \"BinaryExpression\":\n",
    "        node.operator = operatorText(node.operatorToken, ts);\n",
    "        break;\n",
    "      case \"TemplateExpression\":\n",
    "        node.quasis = [node.head].concat(\n",
    "          (node.templateSpans || []).map((s) => s.literal)\n",
    "        );\n",
    "        node.expressions = (node.templateSpans || []).map((s) => s.expression);\n",
    "        break;\n",
    "      case \"TemplateLiteral\":\n",
    "        node.quasis = [{ value: { raw: unquote(node.text) } }];\n",
    "        node.expressions = [];\n",
    "        break;\n",
    "      case \"ArrowFunction\":\n",
    "      case \"FunctionExpression\":\n",
    "      case \"FunctionDeclaration\":\n",
    "        node.params = node.parameters || [];\n",
    "        node.body = node.body || { type: \"BlockStatement\", body: [] };\n",
    "        node.id = node.name;\n",
    "        break;\n",
    "      default:\n",
    "        break;\n",
    "    }\n",
    "\n",
    "    node.type = type;\n",
    "\n",
    "    // Children. `parent` is never read because setParentNodes is false, but\n",
    "    // other back-references exist, so an explicit key list is used.\n",
    "    for (const key of Object.keys(node)) {\n",
    "      if (key === \"parent\" || key === \"loc\" || key === \"type\") continue;\n",
    "      const child = node[key];\n",
    "      if (child && typeof child === \"object\") stack.push(child);\n",
    "    }\n",
    "  }\n",
    "}\n",
    "\n",
    "function unquote(text) {\n",
    "  if (typeof text !== \"string\") return text;\n",
    "  if (text.length >= 2) {\n",
    "    const first = text[0];\n",
    "    const last = text[text.length - 1];\n",
    "    if ((first === '\"' && last === '\"') || (first === \"'\" && last === \"'\")) {\n",
    "      return text.slice(1, -1);\n",
    "    }\n",
    "    if (first === \"`\" && last === \"`\") return text.slice(1, -1);\n",
    "  }\n",
    "  return text;\n",
    "}\n",
    "\n",
    "// Render an expression to a stable, formatting-insensitive string. Opaque\n",
    "// and versioned on both sides, so a parser change cannot alter the comparison.\n",
    "function normalize(node) {\n",
    "  if (!node) return \"\";\n",
    "  switch (node.type) {\n",
    "    case \"Identifier\":\n",
    "    case \"PrivateName\":\n",
    "    case \"PrivateIdentifier\":\n",
    "      return node.name;\n",
    "    case \"NumericLiteral\":\n",
    "    case \"StringLiteral\":\n",
    "    case \"BooleanLiteral\":\n",
    "    case \"BigIntLiteral\":\n",
    "    // ESTree's `Literal` is what acorn emits. Without this case every literal\n",
    "    // normalized to the bare word `Literal`, so `toBe(2)` and `toBe(3)`\n",
    "    // rendered identically and no expectation change was ever reported.\n",
    "    case \"Literal\":\n",
    "      if (node.regex) return String(node.regex.pattern);\n",
    "      if (node.bigint) return node.bigint;\n",
    "      return JSON.stringify(node.value);\n",
    "    case \"NullLiteral\":\n",
    "      return \"null\";\n",
    "    case \"RegExpLiteral\":\n",
    "      return String((node.regex && node.regex.pattern) || node.pattern || \"\");\n",
    "    case \"MemberExpression\":\n",
    "      return (\n",
    "        normalize(node.object) +\n",
    "        (node.computed ? \"[...]\" : \".\" + normalize(node.property))\n",
    "      );\n",
    "    case \"CallExpression\":\n",
    "    case \"OptionalCallExpression\": {\n",
    "      const args = (node.arguments || [])\n",
    "        .filter((a) => a && a.type !== \"SpreadElement\")\n",
    "        .map(normalize);\n",
    "      return normalize(node.callee) + \"(\" + args.join(\", \") + \")\";\n",
    "    }\n",
    "    case \"NewExpression\":\n",
    "      return \"new \" + normalize(node.callee);\n",
    "    case \"BinaryExpression\":\n",
    "    case \"LogicalExpression\": {\n",
    "      const raw = node.operator;\n",
    "      const op = raw === \"===\" ? \"==\" : raw === \"!==\" ? \"!=\" : raw;\n",
    "      return normalize(node.left) + \" \" + op + \" \" + normalize(node.right);\n",
    "    }\n",
    "    case \"UnaryExpression\":\n",
    "      return node.operator + normalize(node.argument);\n",
    "    case \"ConditionalExpression\":\n",
    "      return (\n",
    "        normalize(node.test) +\n",
    "        \" ? \" +\n",
    "        normalize(node.consequent) +\n",
    "        \" : \" +\n",
    "        normalize(node.alternate)\n",
    "      );\n",
    "    case \"ArrayExpression\":\n",
    "      return \"[\" + (node.elements || []).map(normalize).join(\", \") + \"]\";\n",
    "    case \"ObjectExpression\":\n",
    "      return (\n",
    "        \"{\" +\n",
    "        (node.properties || [])\n",
    "          .map((p) => normalize(p.key) + \": \" + normalize(p.value))\n",
    "          .join(\", \") +\n",
    "        \"}\"\n",
    "      );\n",
    "    case \"TemplateLiteral\": {\n",
    "      const exprs = (node.expressions || []).map(normalize);\n",
    "      return (\n",
    "        \"`\" +\n",
    "        (node.quasis || [])\n",
    "          .map((q) => (q.value && q.value.raw !== undefined ? q.value.raw : q.text))\n",
    "          .join(\"${\") +\n",
    "        (exprs.length ? exprs.join(\", \") : \"\") +\n",
    "        \"}`\"\n",
    "      );\n",
    "    }\n",
    "    case \"AwaitExpression\":\n",
    "      return \"await \" + normalize(node.argument);\n",
    "    case \"TSAsExpression\":\n",
    "    case \"TSSatisfiesExpression\":\n",
    "      return normalize(node.expression);\n",
    "    case \"TSNonNullExpression\":\n",
    "      return normalize(node.expression);\n",
    "    default:\n",
    "      // Named rather than guessed, so an unhandled form participates in\n",
    "      // comparison without pretending to be understood.\n",
    "      return node.type;\n",
    "  }\n",
    "}\n",
    "\n",
    "// Assertion helpers, and the matcher each implies.\n",
    "const EQUALITY_MATCHERS = new Set([\"toBe\", \"toEqual\", \"toStrictEqual\"]);\n",
    "const NEGATED = new Set([\"not\"]);\n",
    "const MODIFIERS = new Set([\"resolves\", \"rejects\"]);\n",
    "\n",
    "// Node's `assert` module, and Jest's global `assert`. Both take the actual\n",
    "// value first, unlike JUnit and Minitest, so no argument swap is needed.\n",
    "const ASSERT_EQ_METHODS = {\n",
    "  equal: false,\n",
    "  strictEqual: false,\n",
    "  deepEqual: false,\n",
    "  deepStrictEqual: false,\n",
    "  notEqual: true,\n",
    "  notStrictEqual: true,\n",
    "  notDeepEqual: true,\n",
    "  notDeepStrictEqual: true,\n",
    "  // Jest's global form, same convention.\n",
    "  assertEqual: false,\n",
    "  assertStrictEqual: false,\n",
    "  assertDeepEqual: false,\n",
    "  assertNotEqual: true,\n",
    "  assertNotStrictEqual: true,\n",
    "  assertNotDeepEqual: true,\n",
    "};\n",
    "\n",
    "// `assert(cond)`, `assert.ok(cond)`, `assertTrue(cond)`, `assert.throws(f)`.\n",
    "const ASSERT_PREDICATE_METHODS = new Set([\n",
    "  \"ok\",\n",
    "  \"throws\",\n",
    "  \"doesNotThrow\",\n",
    "  \"rejects\",\n",
    "  \"resolves\",\n",
    "  \"assert\",\n",
    "  \"assertTrue\",\n",
    "  \"assertFalse\",\n",
    "  \"assertTruthy\",\n",
    "  \"assertFalsy\",\n",
    "  \"assertThrows\",\n",
    "  \"assertDoesNotThrow\",\n",
    "  \"assertIfError\",\n",
    "  \"ifError\",\n",
    "]);\n",
    "\n",
    "function isMemberNamed(node, name) {\n",
    "  return (\n",
    "    node &&\n",
    "    node.type === \"MemberExpression\" &&\n",
    "    node.property &&\n",
    "    node.property.type === \"Identifier\" &&\n",
    "    node.property.name === name\n",
    "  );\n",
    "}\n",
    "\n",
    "function isIdentifierNamed(node, name) {\n",
    "  return node && node.type === \"Identifier\" && node.name === name;\n",
    "}\n",
    "\n",
    "// Jest/Vitest: `expect(x).toBe(y)` is a CallExpression whose callee is a\n",
    "// MemberExpression chain. Jest's `assert(x)` is a plain call, and Node's is a\n",
    "// member call on an identifier.\n",
    "function assertionFromCall(node) {\n",
    "  if (node.type !== \"CallExpression\") return null;\n",
    "  const callee = node.callee;\n",
    "  if (!callee) return null;\n",
    "\n",
    "  // ---- `expect(x).toBe(y)`, including `.not` and `.resolves` -------------\n",
    "  if (callee.type === \"MemberExpression\") {\n",
    "    // `assert.strictEqual(actual, expected)` and friends.\n",
    "    if (\n",
    "      (isIdentifierNamed(callee.object, \"assert\") ||\n",
    "        isIdentifierNamed(callee.object, \"chai\")) &&\n",
    "      callee.property &&\n",
    "      callee.property.type === \"Identifier\"\n",
    "    ) {\n",
    "      const method = callee.property.name;\n",
    "      const args = node.arguments || [];\n",
    "      if (Object.prototype.hasOwnProperty.call(ASSERT_EQ_METHODS, method)) {\n",
    "        if (args.length < 2) return null;\n",
    "        const operator = ASSERT_EQ_METHODS[method] ? \" NotEq \" : \" Eq \";\n",
    "        return normalize(args[0]) + operator + normalize(args[1]);\n",
    "      }\n",
    "      if (ASSERT_PREDICATE_METHODS.has(method) && args.length > 0) {\n",
    "        return normalize(args[0]);\n",
    "      }\n",
    "      return null;\n",
    "    }\n",
    "\n",
    "    // Unwrap `.not` and `.resolves`/`.rejects`, which sit between `expect(x)`\n",
    "    // and the matcher. Measured against real acorn: `expect(x).not.toBe(1)` has\n",
    "    // `callee.object` as a *MemberExpression* (`expect(x).not`), not a call, so\n",
    "    // the previous unwrap missed it and every negated expectation produced no\n",
    "    // assertion at all — inverting an expectation went unreported.\n",
    "    let current = callee.object;\n",
    "    let negated = false;\n",
    "    while (\n",
    "      current &&\n",
    "      current.type === \"MemberExpression\" &&\n",
    "      current.property &&\n",
    "      current.property.type === \"Identifier\"\n",
    "    ) {\n",
    "      const name = current.property.name;\n",
    "      if (NEGATED.has(name)) negated = !negated;\n",
    "      else if (!MODIFIERS.has(name)) break;\n",
    "      current = current.object;\n",
    "    }\n",
    "\n",
    "    if (!current || current.type !== \"CallExpression\") return null;\n",
    "    const inner = current.callee;\n",
    "    if (!inner || inner.type !== \"Identifier\") return null;\n",
    "    const helper = inner.name;\n",
    "    if (helper !== \"expect\" && helper !== \"should\") return null;\n",
    "\n",
    "    const args = current.arguments || [];\n",
    "    if (args.length === 0) return null;\n",
    "    const subject = normalize(args[0]);\n",
    "    const matcherName =\n",
    "      callee.property && callee.property.type === \"Identifier\"\n",
    "        ? callee.property.name\n",
    "        : \"\";\n",
    "    const values = (node.arguments || []).map(normalize);\n",
    "    if (EQUALITY_MATCHERS.has(matcherName) && values.length > 0) {\n",
    "      return subject + (negated ? \" NotEq \" : \" Eq \") + values[0];\n",
    "    }\n",
    "    // Every other matcher constrains the subject alone.\n",
    "    return subject;\n",
    "  }\n",
    "\n",
    "  // ---- bare `assert(cond)`, `assertTrue(cond)` ---------------------------\n",
    "  if (callee.type === \"Identifier\") {\n",
    "    const args = node.arguments || [];\n",
    "    if (args.length === 0) return null;\n",
    "    if (Object.prototype.hasOwnProperty.call(ASSERT_EQ_METHODS, callee.name)) {\n",
    "      if (args.length < 2) return null;\n",
    "      const operator = ASSERT_EQ_METHODS[callee.name] ? \" NotEq \" : \" Eq \";\n",
    "      return normalize(args[0]) + operator + normalize(args[1]);\n",
    "    }\n",
    "    if (ASSERT_PREDICATE_METHODS.has(callee.name)) {\n",
    "      return normalize(args[0]);\n",
    "    }\n",
    "  }\n",
    "  return null;\n",
    "}\n",
    "\n",
    "// Walk every node in the tree.\n",
    "function walk(node, visit) {\n",
    "  if (!node || typeof node !== \"object\") return;\n",
    "  if (Array.isArray(node)) {\n",
    "    for (const child of node) walk(child, visit);\n",
    "    return;\n",
    "  }\n",
    "  if (typeof node.type === \"string\") visit(node);\n",
    "  for (const key of Object.keys(node)) {\n",
    "    if (key === \"loc\" || key === \"leadingComments\" || key === \"trailingComments\") {\n",
    "      continue;\n",
    "    }\n",
    "    walk(node[key], visit);\n",
    "  }\n",
    "}\n",
    "\n",
    "const TEST_ROOTS = new Set([\"test\", \"it\", \"specify\"]);\n",
    "const SKIP_MODIFIERS = new Set([\"skip\", \"todo\"]);\n",
    "\n",
    "function rootTestName(callee) {\n",
    "  if (!callee) return null;\n",
    "  if (callee.type === \"Identifier\") {\n",
    "    return TEST_ROOTS.has(callee.name) ? callee.name : null;\n",
    "  }\n",
    "  if (callee.type === \"MemberExpression\") {\n",
    "    if (\n",
    "      callee.object &&\n",
    "      callee.object.type === \"Identifier\" &&\n",
    "      TEST_ROOTS.has(callee.object.name)\n",
    "    ) {\n",
    "      return callee.object.name;\n",
    "    }\n",
    "  }\n",
    "  return null;\n",
    "}\n",
    "\n",
    "function isTestName(name) {\n",
    "  return /^(test|it|specify)(\\.|$)/.test(name) || /^Test|^Spec/.test(name);\n",
    "}\n",
    "\n",
    "// The label is the first string argument, wherever it sits. `test.each(t)('x',\n",
    "// fn)` puts it on the outer call while the callee is itself a call.\n",
    "function labelFor(node) {\n",
    "  const args = node.arguments || [];\n",
    "  const found = args.find(\n",
    "    (a) => a && (a.type === \"Literal\" || a.type === \"StringLiteral\")\n",
    "  );\n",
    "  if (!found) return \"\";\n",
    "  const value = found.value !== undefined ? found.value : found.text;\n",
    "  return value === undefined ? \"\" : String(value);\n",
    "}\n",
    "\n",
    "function summarize(source, file) {\n",
    "  const parsers = loadParsers(PROJECT_DIR);\n",
    "  if (parsers.length === 0) {\n",
    "    return {\n",
    "      format: 1,\n",
    "      error:\n",
    "        \"no JavaScript parser available; install one of @babel/parser, acorn or typescript as a project dependency\",\n",
    "    };\n",
    "  }\n",
    "\n",
    "  let tree = null;\n",
    "  let used = null;\n",
    "  let lastError = null;\n",
    "  for (const parser of parsers) {\n",
    "    try {\n",
    "      const candidate = parseWith(source, parser, file);\n",
    "      if (candidate) {\n",
    "        tree = candidate;\n",
    "        used = parser;\n",
    "        break;\n",
    "      }\n",
    "    } catch (error) {\n",
    "      // A parser that cannot read this file is not the end of the search: the\n",
    "      // next one may be the one this file needs.\n",
    "      lastError = error;\n",
    "    }\n",
    "  }\n",
    "  if (!tree) {\n",
    "    return {\n",
    "      format: 1,\n",
    "      error: String(\n",
    "        lastError && lastError.message ? lastError.message : \"could not parse\"\n",
    "      ),\n",
    "    };\n",
    "  }\n",
    "\n",
    "  // `test.each(table)(...)` — the inner call passes the table and is never a\n",
    "  // test on its own; the outer call carries the label and the body. Reporting\n",
    "  // the inner one too produced a second, assertion-less function that looked\n",
    "  // like an empty test.\n",
    "  const TABLE_MODIFIERS = new Set([\"each\", \"forEach\"]);\n",
    "\n",
    "  function isTableOnlyCall(node) {\n",
    "    if (!node || node.type !== \"CallExpression\" || !node.callee) return false;\n",
    "    if (node.callee.type !== \"MemberExpression\") return false;\n",
    "    if (!rootTestName(node.callee)) return false;\n",
    "    const modifier = node.callee.property && node.callee.property.name;\n",
    "    return TABLE_MODIFIERS.has(modifier);\n",
    "  }\n",
    "\n",
    "  const functions = [];\n",
    "  walk(tree, (node) => {\n",
    "    if (node.type !== \"CallExpression\") return;\n",
    "    if (isTableOnlyCall(node)) return;\n",
    "\n",
    "    // A test is a call to `test`/`it`/`specify`, possibly through a modifier\n",
    "    // (`test.skip`, `it.only`, `test.each(table)`). Measured against real\n",
    "    // acorn: only the bare form was recognized, so `test.skip` produced *no\n",
    "    // function at all* and newly skipping a test was invisible.\n",
    "    // `test.each(table)('label', fn)` wraps the real call in an outer call whose\n",
    "    // callee is itself a call. The outer one is the test, because only it\n",
    "    // carries the label and the body; treating the inner one as a test\n",
    "    // produced a second function with no assertions at all.\n",
    "    let calleeForRoot = node.callee;\n",
    "    if (\n",
    "      calleeForRoot &&\n",
    "      calleeForRoot.type === \"CallExpression\" &&\n",
    "      rootTestName(calleeForRoot.callee)\n",
    "    ) {\n",
    "      calleeForRoot = calleeForRoot.callee;\n",
    "    }\n",
    "    const helper = rootTestName(calleeForRoot);\n",
    "    if (helper) {\n",
    "      let skipped = false;\n",
    "      let callee = calleeForRoot;\n",
    "      while (callee && callee.type === \"MemberExpression\") {\n",
    "        const name = callee.property && callee.property.name;\n",
    "        if (name && SKIP_MODIFIERS.has(name)) skipped = true;\n",
    "        callee = callee.object;\n",
    "      }\n",
    "      const label = labelFor(node);\n",
    "      const name = label\n",
    "        ? `${helper}: ${label}`\n",
    "        : `${helper}@${node.loc ? node.loc.start.line : 0}`;\n",
    "      functions.push(collectBody(name, node.loc ? node.loc.start.line : 0, node, skipped));\n",
    "      return;\n",
    "    }\n",
    "\n",
    "    // A Minitest-style `function test_foo() {}` or `const test = () => {}`.\n",
    "    if (node.type === \"FunctionDeclaration\" && node.id && isTestName(node.id.name)) {\n",
    "      functions.push(collectBody(node.id.name, node.loc ? node.loc.start.line : 0, node, false));\n",
    "      return;\n",
    "    }\n",
    "    if (\n",
    "      node.type === \"VariableDeclarator\" &&\n",
    "      node.id &&\n",
    "      node.id.type === \"Identifier\" &&\n",
    "      isTestName(node.id.name) &&\n",
    "      node.init &&\n",
    "      (node.init.type === \"ArrowFunctionExpression\" || node.init.type === \"FunctionExpression\")\n",
    "    ) {\n",
    "      functions.push(collectBody(node.id.name, node.loc ? node.loc.start.line : 0, node.init, false));\n",
    "    }\n",
    "  });\n",
    "\n",
    "  return { format: 1, parser: used.name, functions };\n",
    "}\n",
    "\n",
    "function collectBody(name, line, node, skipped) {\n",
    "  const assertions = [];\n",
    "  const guards = [];\n",
    "  const bindings = {};\n",
    "  const seen = new Set();\n",
    "\n",
    "  walk(node, (child) => {\n",
    "    const found = assertionFromCall(child);\n",
    "    if (found !== null && found !== \"\") {\n",
    "      // `expect(x).not.toBe(1)` is one expectation. Without deduplication the\n",
    "      // traversal reports both the inner and the outer call, inventing a\n",
    "      // second assertion that the source does not contain.\n",
    "      const key = child.loc ? child.loc.start.line + \"|\" + found : found;\n",
    "      if (seen.has(key)) return;\n",
    "      seen.add(key);\n",
    "      assertions.push({ line: child.loc ? child.loc.start.line : 0, test: found });\n",
    "    }\n",
    "    // A thrown assertion is a failure guard, not an expectation.\n",
    "    if (\n",
    "      child.type === \"IfStatement\" &&\n",
    "      child.consequent &&\n",
    "      child.consequent.type === \"BlockStatement\"\n",
    "    ) {\n",
    "      const throws = (child.consequent.body || []).some(\n",
    "        (s) =>\n",
    "          s.type === \"ThrowStatement\" ||\n",
    "          (s.type === \"ExpressionStatement\" &&\n",
    "            s.expression &&\n",
    "            s.expression.type === \"CallExpression\" &&\n",
    "            s.expression.callee &&\n",
    "            (s.expression.callee.name === \"fail\" ||\n",
    "              s.expression.callee.name === \"assert\"))\n",
    "      );\n",
    "      if (throws) guards.push(normalize(child.test));\n",
    "    }\n",
    "  });\n",
    "\n",
    "  return {\n",
    "    name,\n",
    "    line,\n",
    "    assertions,\n",
    "    skipped: Boolean(skipped),\n",
    "    body_is_empty: assertions.length === 0 && guards.length === 0,\n",
    "    bindings,\n",
    "    guards,\n",
    "  };\n",
    "}\n",
    "\n",
    "let PROJECT_DIR = null;\n",
    "\n",
    "function main() {\n",
    "  const file = process.argv[2];\n",
    "  PROJECT_DIR = process.argv[3] || process.cwd();\n",
    "  try {\n",
    "    const source = fs.readFileSync(file, \"utf-8\");\n",
    "    process.stdout.write(JSON.stringify(summarize(source, file)));\n",
    "  } catch (error) {\n",
    "    process.stdout.write(\n",
    "      JSON.stringify({ format: 1, error: String(error && error.message ? error.message : error) })\n",
    "    );\n",
    "  }\n",
    "}\n",
    "\n",
    "main();\n",
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_tool_has_the_expected_shape() {
        assert!(SUMMARY_SCRIPT.contains("PARSERS"));
        assert!(SUMMARY_SCRIPT.contains("@babel/parser"));
        assert!(SUMMARY_SCRIPT.contains("acorn"));
        assert!(SUMMARY_SCRIPT.contains("typescript"));
    }

    /// The parser must be required from the project, never bundled, and its
    /// absence must be reported rather than worked around.
    #[test]
    fn a_missing_parser_is_reported() {
        assert!(SUMMARY_SCRIPT.contains("no JavaScript parser available"));
        assert!(
            !SUMMARY_SCRIPT.contains("require(\"acorn\")"),
            "the parser must be resolved dynamically, not hard-required"
        );
    }

    /// `.not` sits between `expect(x)` and the matcher, so the unwrap has to
    /// descend through it. Reading the base without unwrapping returned nothing
    /// for every negated expectation.
    ///
    /// This used to assert on the script's *text*, which is why the real-acorn
    /// bug passed it: the text was present, but the traversal still missed the
    /// shape acorn produces. The end-to-end coverage in
    /// `tests/javascript_analysis.rs` is what actually pins this down; these
    /// tests assert on structure, not wording.
    #[test]
    fn the_tool_unwraps_negation_and_matchers() {
        assert!(SUMMARY_SCRIPT.contains("NEGATED"));
        assert!(SUMMARY_SCRIPT.contains("MODIFIERS"));
        assert!(SUMMARY_SCRIPT.contains("current = current.object"));
    }

    /// Node's `assert` module and Jest's global `assert` were invisible: only a
    /// bare `assert*(...)` call was recognized, and the member-call form Node
    /// actually ships was not. Found by running against real acorn.
    #[test]
    fn the_tool_recognizes_the_node_assert_module() {
        assert!(SUMMARY_SCRIPT.contains("ASSERT_EQ_METHODS"));
        assert!(SUMMARY_SCRIPT.contains("strictEqual"));
        assert!(SUMMARY_SCRIPT.contains("deepStrictEqual"));
    }

    /// ESTree's `Literal` is acorn's node type. Without it every literal
    /// normalized to the bare word `Literal`, so `toBe(2)` and `toBe(3)`
    /// rendered identically and no expectation change was ever reported.
    #[test]
    fn the_tool_normalizes_estree_literals() {
        assert!(SUMMARY_SCRIPT.contains("case \"Literal\""));
    }

    /// The TypeScript AST tags nodes with `kind`, not `type`, so a traversal
    /// written for ESTree visited nothing. Measured against real `typescript`:
    /// every `.ts` file analyzed as zero tests, and with `setParentNodes` on the
    /// tree was cyclic and recursed until the stack overflowed.
    #[test]
    fn the_tool_annotates_the_typescript_ast() {
        assert!(SUMMARY_SCRIPT.contains("annotateTypeScript"));
        assert!(
            SUMMARY_SCRIPT.contains("false,"),
            "setParentNodes must be false, or the parent back-pointer cycles"
        );
    }

    /// A parser that cannot read a file is not the end of the search. Choosing
    /// purely on which parser is installed meant a TypeScript project with acorn
    /// present failed on every `.ts` file.
    #[test]
    fn the_tool_tries_every_available_parser() {
        assert!(SUMMARY_SCRIPT.contains("loadParsers"));
    }

    /// Equality matchers normalize to the canonical subject-first form; every
    /// other matcher constrains the subject alone.
    #[test]
    fn the_tool_normalizes_equality_matchers() {
        assert!(SUMMARY_SCRIPT.contains("EQUALITY_MATCHERS"));
        assert!(SUMMARY_SCRIPT.contains(" NotEq "));
        assert!(SUMMARY_SCRIPT.contains(" Eq "));
    }
    /// Node resolves `require` relative to the *script's* directory, not the
    /// working directory, so a tool in a temp directory cannot see the
    /// project's node_modules however it is invoked. Verified directly. The
    /// project directory is therefore passed explicitly and each candidate is
    /// required by absolute path.
    #[test]
    fn the_tool_resolves_the_parser_by_absolute_path() {
        assert!(SUMMARY_SCRIPT.contains("node_modules"));
        assert!(SUMMARY_SCRIPT.contains("require.resolve"));
        assert!(SUMMARY_SCRIPT.contains("projectDir"));
    }
}
