//! The PHP summary tool, embedded so there is no separate file to locate at
//! runtime.
//!
//! WitDiff writes this to a temporary file and runs it with the interpreter the
//! project's own test command names (ADR-0023). `token_get_all` ships in every
//! PHP installation, so no Composer dependency is required and the analysis
//! works in any project that can run its tests.
//!
//! Both assertion styles are normalized to the same canonical, subject-first
//! form: PHPUnit's `assertEquals(expected, actual)` and Pest's
//! `expect($x)->toBe($y)`. `token_get_all` is a tokenizer rather than a parser,
//! so node shapes are read from the real token stream rather than assumed —
//! which is what caught three separate bugs: PHP 8 emits `->` as one
//! `T_OBJECT_OPERATOR` token rather than `-` and `>`, a Pest closure's body sits
//! *inside* the call's parentheses rather than after them, and a subject like
//! `(new Calc(1, 2))->add()` contains its own `->` and would otherwise be read
//! as the expectation's matcher.

/// The tool's format version.
pub const SUMMARY_FORMAT: u32 = 1;

/// Emit a normalized structural summary of one PHP test file as JSON.
pub const SUMMARY_SCRIPT: &str = concat!(
    "<?php\n",
    "/**\n",
    " * Structural summary tool for PHP test files (ADR-0023).\n",
    " *\n",
    " * Run as: php summarize.php <path>\n",
    " *\n",
    " * Uses token_get_all, which ships with every PHP installation. That is the same\n",
    " * reasoning as Ruby's ripper and Python's ast: the parser the project already\n",
    " * has, rather than a dependency WitDiff would have to install or require the\n",
    " * project to have.\n",
    " *\n",
    " * token_get_all is a tokenizer, not a parser, so there is no tree to walk.\n",
    " * Brace depth is tracked instead: a function body opens at the first `{` after\n",
    " * the declaration's parameter list and closes at the matching `}`. That is\n",
    " * enough to find test methods, the assertions inside them, and the arguments\n",
    " * those assertions compare — which is what the shared rule engine needs.\n",
    " */\n",
    "\n",
    "declare(strict_types=1);\n",
    "\n",
    "/**\n",
    " * A test method: name, line, assertions.\n",
    " *\n",
    " * @return array<int, array<string, mixed>>\n",
    " */\n",
    "function summarizeTestFile(string $path): array\n",
    "{\n",
    "    $source = @file_get_contents($path);\n",
    "    if ($source === false) {\n",
    "        throw new RuntimeException(\"could not read $path\");\n",
    "    }\n",
    "\n",
    "    $tokens = @token_get_all($source);\n",
    "    $functions = [];\n",
    "    $current = null;\n",
    "    $depth = 0;\n",
    "\n",
    "    // Body brace depth of the function currently being collected.\n",
    "    $functionDepth = null;\n",
    "    // Brace depth at which the current function's parameter list opened.\n",
    "    $pendingDepth = null;\n",
    "\n",
    "    $count = count($tokens);\n",
    "    for ($i = 0; $i < $count; $i++) {\n",
    "        $token = $tokens[$i];\n",
    "        $text = is_array($token) ? $token[1] : $token;\n",
    "        $id = is_array($token) ? $token[0] : null;\n",
    "        $line = is_array($token) ? $token[2] : null;\n",
    "\n",
    "        if ($text === '{') {\n",
    "            $depth++;\n",
    "            // The first `{` after a test declaration's parameter list opens its body.\n",
    "            if ($current !== null && $pendingDepth !== null && $depth === $pendingDepth) {\n",
    "                $functionDepth = $depth;\n",
    "                $pendingDepth = null;\n",
    "            }\n",
    "            continue;\n",
    "        }\n",
    "        if ($text === '}') {\n",
    "            $depth--;\n",
    "            if ($current !== null && $functionDepth !== null && $depth < $functionDepth) {\n",
    "                $functions[] = $current;\n",
    "                $current = null;\n",
    "                $functionDepth = null;\n",
    "            }\n",
    "            continue;\n",
    "        }\n",
    "\n",
    "        // Pest: `test('name', function () { ... });` — a call whose second\n",
    "        // argument is the closure. Collected here rather than by the `function`\n",
    "        // branch below, because a closure has no name to read and is preceded\n",
    "        // by a `T_STRING`, not a `T_FUNCTION`.\n",
    "        if ($id === T_STRING && ($text === 'test' || $text === 'it')) {\n",
    "            $example = pestExample($tokens, $i);\n",
    "            if ($example !== null) {\n",
    "                $functions[] = $example['function'];\n",
    "                // Skip past the whole call so the closure's own `function`\n",
    "                // token is not re-read as a declaration.\n",
    "                $i = $example['end'];\n",
    "            }\n",
    "            continue;\n",
    "        }\n",
    "\n",
    "        // A `function` keyword begins a declaration. The name is the next\n",
    "        // identifier, and the body opens at the `{` that follows its\n",
    "        // parameter list.\n",
    "        if ($id === T_FUNCTION) {\n",
    "            $name = nextIdentifier($tokens, $i);\n",
    "            if ($name !== null && isTestMethodName($name['name'])) {\n",
    "                $current = [\n",
    "                    'name' => $name['name'],\n",
    "                    'line' => $name['line'],\n",
    "                    'assertions' => [],\n",
    "                    'skipped' => false,\n",
    "                    'body_is_empty' => false,\n",
    "                    'bindings' => (object) [],\n",
    "                    'guards' => [],\n",
    "                ];\n",
    "                $pendingDepth = $depth + 1;\n",
    "                $functionDepth = null;\n",
    "            }\n",
    "            $i = $name !== null ? $name['index'] : $i;\n",
    "            continue;\n",
    "        }\n",
    "\n",
    "        if ($current === null) {\n",
    "            continue;\n",
    "        }\n",
    "\n",
    "        $assertion = assertionFromCall($tokens, $i);\n",
    "        if ($assertion !== null) {\n",
    "            $current['assertions'][] = [\n",
    "                'line' => $assertion['line'] ?? 0,\n",
    "                'test' => $assertion['text'],\n",
    "            ];\n",
    "        }\n",
    "    }\n",
    "\n",
    "    return $functions;\n",
    "}\n",
    "\n",
    "\n",
    "/**\n",
    " * Collect a Pest example: `test('name', function () { ... })`.\n",
    " *\n",
    " * The example name is the first string argument. The body is the first `{`\n",
    " * inside the call's parentheses — the closure is an *argument*, so its braces\n",
    " * come before the call's closing paren, not after it.\n",
    " *\n",
    " * @param array<int, array{0:int,1:string,2:int}|string> $tokens\n",
    " * @return array{function: array<string, mixed>, end: int}|null\n",
    " */\n",
    "function pestExample(array $tokens, int $i): ?array\n",
    "{\n",
    "    $args = callArguments($tokens, $i);\n",
    "    if ($args === null || $args === []) {\n",
    "        return null;\n",
    "    }\n",
    "    $name = $args[0];\n",
    "    if (!str_starts_with($name, \"'\") && !str_starts_with($name, '\"')) {\n",
    "        return null;\n",
    "    }\n",
    "    $name = trim($name, \"'\\\"\");\n",
    "\n",
    "    $count = count($tokens);\n",
    "    $open = null;\n",
    "    $parenDepth = 0;\n",
    "    for ($m = $i + 1; $m < $count; $m++) {\n",
    "        $token = $tokens[$m];\n",
    "        $text = is_array($token) ? $token[1] : $token;\n",
    "        // Only a `{` at the call's own top level opens the body. A closure's\n",
    "        // parameter list closes its own parens first, so `)` is not by itself\n",
    "        // the end of the call — the depth is what tells them apart.\n",
    "        if ($text === '{' && $parenDepth === 1) {\n",
    "            $open = $m;\n",
    "            break;\n",
    "        }\n",
    "        if ($text === '(') {\n",
    "            $parenDepth++;\n",
    "        } elseif ($text === ')') {\n",
    "            $parenDepth--;\n",
    "            if ($parenDepth === 0) {\n",
    "                return null;\n",
    "            }\n",
    "        } elseif ($text === ';' && $parenDepth === 0) {\n",
    "            return null;\n",
    "        }\n",
    "    }\n",
    "    if ($open === null) {\n",
    "        return null;\n",
    "    }\n",
    "\n",
    "    $bodyDepth = 0;\n",
    "    $collected = [];\n",
    "    for ($m = $open; $m < $count; $m++) {\n",
    "        $token = $tokens[$m];\n",
    "        $text = is_array($token) ? $token[1] : $token;\n",
    "        if ($text === '{') {\n",
    "            $bodyDepth++;\n",
    "            continue;\n",
    "        }\n",
    "        if ($text === '}') {\n",
    "            $bodyDepth--;\n",
    "            if ($bodyDepth === 0) {\n",
    "                return [\n",
    "                    'function' => [\n",
    "                        'name' => $name,\n",
    "                        'line' => is_array($tokens[$i]) ? $tokens[$i][2] : 0,\n",
    "                        'assertions' => $collected,\n",
    "                        'skipped' => false,\n",
    "                        'body_is_empty' => $collected === [],\n",
    "                        'bindings' => (object) [],\n",
    "                        'guards' => [],\n",
    "                    ],\n",
    "                    'end' => $m,\n",
    "                ];\n",
    "            }\n",
    "            continue;\n",
    "        }\n",
    "        $assertion = assertionFromCall($tokens, $m);\n",
    "        if ($assertion !== null) {\n",
    "            $collected[] = ['line' => $assertion['line'], 'test' => $assertion['text']];\n",
    "        }\n",
    "    }\n",
    "    return null;\n",
    "}\n",
    "\n",
    "/**\n",
    " * The identifier that follows a `function` keyword, with its token index.\n",
    " *\n",
    " * @param array<int, array{0:int,1:string,2:int}|string> $tokens\n",
    " * @return array{name: string, line: int, index: int}|null\n",
    " */\n",
    "function nextIdentifier(array $tokens, int $from): ?array\n",
    "{\n",
    "    $count = count($tokens);\n",
    "    for ($j = $from + 1; $j < $count; $j++) {\n",
    "        $token = $tokens[$j];\n",
    "        if (!is_array($token)) {\n",
    "            // A `&` marks a by-reference return; keep looking.\n",
    "            if ($token === '&') {\n",
    "                continue;\n",
    "            }\n",
    "            return null;\n",
    "        }\n",
    "        if ($token[0] === T_WHITESPACE || $token[0] === T_COMMENT || $token[0] === T_DOC_COMMENT) {\n",
    "            continue;\n",
    "        }\n",
    "        if ($token[0] === T_STRING) {\n",
    "            return ['name' => $token[1], 'line' => $token[2], 'index' => $j];\n",
    "        }\n",
    "        return null;\n",
    "    }\n",
    "    return null;\n",
    "}\n",
    "\n",
    "/**\n",
    " * Whether a function name looks like a test method.\n",
    " *\n",
    " * PHPUnit prefixes test methods with `test`; Pest uses `test('name', ...)`\n",
    " * closures, which are collected separately.\n",
    " */\n",
    "function isTestMethodName(string $name): bool\n",
    "{\n",
    "    return str_starts_with($name, 'test')\n",
    "        || str_contains(strtolower($name), 'test')\n",
    "        && preg_match('/test/i', $name) === 1\n",
    "        && !str_starts_with($name, 'latest')\n",
    "        && $name !== 'contest';\n",
    "}\n",
    "\n",
    "/**\n",
    " * Recognize an assertion call at `$i` and render it subject-first.\n",
    " *\n",
    " * PHPUnit and Pest both put the expectation first, so the arguments are swapped\n",
    " * to match the canonical form the shared engine compares. This is the same\n",
    " * correction made for JUnit and Minitest.\n",
    " *\n",
    " * @param array<int, array{0:int,1:string,2:int}|string> $tokens\n",
    " * @return array{text: string, line: int}|null\n",
    " */\n",
    "function assertionFromCall(array $tokens, int $i): ?array\n",
    "{\n",
    "    $count = count($tokens);\n",
    "    $token = $tokens[$i];\n",
    "    $text = is_array($token) ? $token[1] : $token;\n",
    "\n",
    "    // `assertEquals(...)`, `$this->assertEquals(...)`, `self::assertTrue(...)`\n",
    "    if (is_array($token) && $token[0] === T_STRING && isAssertionMethod($token[1])) {\n",
    "        $args = callArguments($tokens, $i);\n",
    "        if ($args === null || $args === []) {\n",
    "            return null;\n",
    "        }\n",
    "        return [\n",
    "            'text' => renderAssertion($token[1], $args),\n",
    "            'line' => $token[2],\n",
    "        ];\n",
    "    }\n",
    "\n",
    "    // Pest: `expect($value)->toBe($expected)`\n",
    "    if (is_array($token) && $token[0] === T_STRING && $token[1] === 'expect') {\n",
    "        $args = callArguments($tokens, $i);\n",
    "        if ($args === null || $args === []) {\n",
    "            return null;\n",
    "        }\n",
    "        $subject = $args[0];\n",
    "        $matcher = chainedMatcher($tokens, $i);\n",
    "        if ($matcher === null) {\n",
    "            return null;\n",
    "        }\n",
    "        return [\n",
    "            'text' => renderExpectation($subject, $matcher['name'], $matcher['args']),\n",
    "            'line' => $token[2],\n",
    "        ];\n",
    "    }\n",
    "\n",
    "    return null;\n",
    "}\n",
    "\n",
    "/**\n",
    " * @param array<int, string> $args\n",
    " */\n",
    "function renderAssertion(string $method, array $args): string\n",
    "{\n",
    "    // Binary comparisons put the expectation first, exactly like JUnit.\n",
    "    if (in_array($method, [\n",
    "        'assertEquals', 'assertSame', 'assertNotEquals', 'assertNotSame',\n",
    "        'assertNotSame', 'assertEqualsCanonicalizing',\n",
    "    ], true) && count($args) >= 2) {\n",
    "        $negated = str_contains($method, 'Not') ? 'NotEq' : 'Eq';\n",
    "        return $args[1] . ' ' . $negated . ' ' . $args[0];\n",
    "    }\n",
    "\n",
    "    // Predicates constrain the subject alone.\n",
    "    return $args[0];\n",
    "}\n",
    "\n",
    "/**\n",
    " * @param array<int, string> $args\n",
    " */\n",
    "function renderExpectation(string $subject, string $matcher, array $args): string\n",
    "{\n",
    "    $negated = match ($matcher) {\n",
    "        'not', 'notToBe', 'toBe' => $matcher === 'not' ? 'NotEq' : 'Eq',\n",
    "        default => null,\n",
    "    };\n",
    "    if ($negated !== null && $args !== []) {\n",
    "        return $subject . ' ' . $negated . ' ' . $args[0];\n",
    "    }\n",
    "    return $subject;\n",
    "}\n",
    "\n",
    "/**\n",
    " * The method name if it is an assertion helper.\n",
    " */\n",
    "function isAssertionMethod(string $name): bool\n",
    "{\n",
    "    if (str_starts_with($name, 'assert')) {\n",
    "        return true;\n",
    "    }\n",
    "    // Pest's expectation methods, and the `markTestSkipped` family that a\n",
    "    // structural comparison needs to see separately.\n",
    "    return in_array($name, ['markTestSkipped', 'markTestIncomplete'], true);\n",
    "}\n",
    "\n",
    "/**\n",
    " * The rendered arguments of a call whose `(` follows at `$i`.\n",
    " *\n",
    " * Splits on top-level commas so `assertSame([1, 2], $x)` stays one argument.\n",
    " *\n",
    " * @param array<int, array{0:int,1:string,2:int}|string> $tokens\n",
    " * @return array<int, string>|null\n",
    " */\n",
    "function callArguments(array $tokens, int $i): ?array\n",
    "{\n",
    "    $count = count($tokens);\n",
    "    $j = $i + 1;\n",
    "    // Skip to the opening parenthesis.\n",
    "    while ($j < $count) {\n",
    "        $token = $tokens[$j];\n",
    "        $text = is_array($token) ? $token[1] : $token;\n",
    "        if ($text === '(') {\n",
    "            break;\n",
    "        }\n",
    "        if (!is_array($token) || $token[0] !== T_WHITESPACE) {\n",
    "            return null;\n",
    "        }\n",
    "        $j++;\n",
    "    }\n",
    "    if ($j >= $count) {\n",
    "        return null;\n",
    "    }\n",
    "\n",
    "    $args = [];\n",
    "    $current = '';\n",
    "    $depth = 0;\n",
    "    $sawContent = false;\n",
    "    for ($k = $j; $k < $count; $k++) {\n",
    "        $token = $tokens[$k];\n",
    "        $text = is_array($token) ? $token[1] : $token;\n",
    "\n",
    "        if ($text === '(' || $text === '[') {\n",
    "            $depth++;\n",
    "            if ($depth === 1) {\n",
    "                continue;\n",
    "            }\n",
    "        }\n",
    "        if ($text === ')' || $text === ']') {\n",
    "            $depth--;\n",
    "            if ($depth === 0) {\n",
    "                if ($sawContent) {\n",
    "                    $args[] = renderExpression($current);\n",
    "                }\n",
    "                return $args;\n",
    "            }\n",
    "        }\n",
    "        if ($text === ',' && $depth === 1) {\n",
    "            $args[] = renderExpression($current);\n",
    "            $current = '';\n",
    "            $sawContent = false;\n",
    "            continue;\n",
    "        }\n",
    "        $sawContent = $sawContent || $text !== '';\n",
    "        $current .= $text;\n",
    "    }\n",
    "    return null;\n",
    "}\n",
    "\n",
    "/**\n",
    " * A Pest expectation chain after an `expect(...)` call: `->toBe(2)`.\n",
    " *\n",
    " * `->` is two tokens, so the method name is the identifier following `>`.\n",
    " *\n",
    " * @param array<int, array{0:int,1:string,2:int}|string> $tokens\n",
    " * @return array{name: string, args: array<int, string>}|null\n",
    " */\n",
    "function chainedMatcher(array $tokens, int $i): ?array\n",
    "{\n",
    "    if (callArguments($tokens, $i) === null) {\n",
    "        return null;\n",
    "    }\n",
    "    // Scan from the end of the `expect(...)` argument list, not from `expect`\n",
    "    // itself: a subject like `(new Calc(1, 2))->add()` contains its own `->`,\n",
    "    // and matching that one would read the subject's own method as the matcher.\n",
    "    $start = closingParen($tokens, $i);\n",
    "    if ($start === null) {\n",
    "        return null;\n",
    "    }\n",
    "    $count = count($tokens);\n",
    "    for ($k = $start; $k < $count; $k++) {\n",
    "        $token = $tokens[$k];\n",
    "        if (!is_array($token) || $token[0] !== T_OBJECT_OPERATOR) {\n",
    "            continue;\n",
    "        }\n",
    "        $m = nextIdentifier($tokens, $k);\n",
    "        if ($m === null) {\n",
    "            return null;\n",
    "        }\n",
    "        $inner = callArguments($tokens, $m['index']);\n",
    "        return ['name' => $m['name'], 'args' => $inner ?? []];\n",
    "    }\n",
    "    return null;\n",
    "}\n",
    "\n",
    "/**\n",
    " * The index of the `)` closing the call whose `(` follows `$i`.\n",
    " *\n",
    " * @param array<int, array{0:int,1:string,2:int}|string> $tokens\n",
    " */\n",
    "function closingParen(array $tokens, int $i): ?int\n",
    "{\n",
    "    $count = count($tokens);\n",
    "    $j = $i + 1;\n",
    "    while ($j < $count) {\n",
    "        $token = $tokens[$j];\n",
    "        $text = is_array($token) ? $token[1] : $token;\n",
    "        if ($text === '(') {\n",
    "            break;\n",
    "        }\n",
    "        if (!is_array($token) || $token[0] !== T_WHITESPACE) {\n",
    "            return null;\n",
    "        }\n",
    "        $j++;\n",
    "    }\n",
    "    if ($j >= $count) {\n",
    "        return null;\n",
    "    }\n",
    "\n",
    "    $depth = 0;\n",
    "    for ($k = $j; $k < $count; $k++) {\n",
    "        $token = $tokens[$k];\n",
    "        $text = is_array($token) ? $token[1] : $token;\n",
    "        if ($text === '(') {\n",
    "            $depth++;\n",
    "        } elseif ($text === ')') {\n",
    "            $depth--;\n",
    "            if ($depth === 0) {\n",
    "                return $k;\n",
    "            }\n",
    "        }\n",
    "    }\n",
    "    return null;\n",
    "}\n",
    "\n",
    "/**\n",
    " * Render an argument expression without internal whitespace, so formatting\n",
    " * differences are not reported as changes.\n",
    " */\n",
    "function renderExpression(string $expression): string\n",
    "{\n",
    "    $collapsed = preg_replace('/\\s+/', ' ', $expression) ?? $expression;\n",
    "    return trim($collapsed);\n",
    "}\n",
    "\n",
    "// ---------------------------------------------------------------------------\n",
    "// Entry point\n",
    "// ---------------------------------------------------------------------------\n",
    "\n",
    "$target = $argv[1] ?? null;\n",
    "if ($target === null || !is_file($target)) {\n",
    "    fwrite(STDERR, \"usage: php summarize.php <path>\\n\");\n",
    "    exit(2);\n",
    "}\n",
    "\n",
    "try {\n",
    "    $functions = summarizeTestFile($target);\n",
    "    echo json_encode(['format' => 1, 'functions' => $functions], JSON_UNESCAPED_SLASHES);\n",
    "} catch (Throwable $error) {\n",
    "    echo json_encode(['format' => 1, 'error' => $error->getMessage()]);\n",
    "}\n",
);
