//! The Ruby summary tool, embedded so there is no separate file to locate at
//! runtime.
//!
//! WitDiff writes this to a temporary file and runs it with the interpreter the
//! project's own test command names (ADR-0020). `ripper` ships in Ruby's
//! standard library, so no gem is required and the analysis works in any
//! project that can run its tests.

/// The tool's format version.
pub const SUMMARY_FORMAT: u32 = 1;

/// Emit a normalized structural summary of one Ruby test file as JSON.
pub const SUMMARY_SCRIPT: &str = concat!(
    "# Summary tool for Ruby test files, using ripper from the standard library\n",
    "# (ADR-0020). Run as: ruby summarize.rb <path>\n",
    "require \"ripper\"\n",
    "require \"json\"\n",
    "\n",
    "# Render a node to a stable, formatting-insensitive string. This form is ours,\n",
    "# and both sides are versioned together, so a ripper change cannot alter the\n",
    "# comparison.\n",
    "def normalize(node)\n",
    "  return \"nil\" if node.nil?\n",
    "  return node.to_s unless node.is_a?(Array)\n",
    "\n",
    "  type = node[0]\n",
    "  case type\n",
    "  when :@int, :@float, :@rational, :@imaginary\n",
    "    node[1]\n",
    "  when :@ident, :@const, :@ivar, :@gvar, :@cvar, :@kw, :@op\n",
    "    node[1]\n",
    "  when :@label\n",
    "    node[1].to_s\n",
    "  when :@tstring_content\n",
    "    node[1].inspect\n",
    "  when :string_literal, :symbol_literal\n",
    "    normalize(node[1])\n",
    "  when :var_ref, :vcall, :const_ref\n",
    "    normalize(node[1])\n",
    "  when :call\n",
    "    receiver = node[1]\n",
    "    name = node[3].is_a?(Array) ? node[3][1] : node[3].to_s\n",
    "    args = node[4]\n",
    "    rendered = args.is_a?(Array) ? normalize_args(args) : []\n",
    "    if receiver.nil?\n",
    "      \"#{name}(#{rendered.join(', ')})\"\n",
    "    else\n",
    "      \"#{normalize(receiver)}.#{name}(#{rendered.join(', ')})\"\n",
    "    end\n",
    "  when :method_add_arg, :command, :command_call\n",
    "    render_call(node)\n",
    "  when :if, :unless\n",
    "    normalize(node[1])\n",
    "  when :binary\n",
    "    \"#{normalize(node[1])} #{node[2]} #{normalize(node[3])}\"\n",
    "  when :unary\n",
    "    \"#{node[1]}#{normalize(node[2])}\"\n",
    "  when :paren\n",
    "    normalize(node[1])\n",
    "  when :array\n",
    "    \"[#{normalize_elements(node[1]).join(', ')}]\"\n",
    "  when :hash\n",
    "    \"{#{normalize_elements(node[1]).join(', ')}}\"\n",
    "  when :dot2, :dot3\n",
    "    \"#{normalize(node[1])}..#{normalize(node[2])}\"\n",
    "  else\n",
    "    type.to_s\n",
    "  end\n",
    "end\n",
    "\n",
    "def render_call(node)\n",
    "  if node[0] == :method_add_arg\n",
    "    inner = node[1]\n",
    "    args = node[2]\n",
    "    rendered = normalize_args(args)\n",
    "    if inner.is_a?(Array) && inner[0] == :call\n",
    "      receiver = inner[1]\n",
    "      name = inner[3].is_a?(Array) ? inner[3][1] : inner[3].to_s\n",
    "      return \"#{name}(#{rendered.join(', ')})\" if receiver.nil?\n",
    "      return \"#{normalize(receiver)}.#{name}(#{rendered.join(', ')})\"\n",
    "    end\n",
    "    # A bare method call is wrapped in :fcall, whose name must be unwrapped\n",
    "    # or the rendering loses the method name.\n",
    "    if inner.is_a?(Array) && inner[0] == :fcall\n",
    "      name = inner[1].is_a?(Array) ? inner[1][1] : inner[1].to_s\n",
    "      return \"#{name}(#{rendered.join(', ')})\"\n",
    "    end\n",
    "    return \"#{normalize(inner)}(#{rendered.join(', ')})\"\n",
    "  end\n",
    "  # :command and :command_call carry the name and args without parens.\n",
    "  name = node[1].is_a?(Array) ? node[1][1] : node[1].to_s\n",
    "  args = normalize_args(node[2])\n",
    "  return \"#{name}(#{args.join(', ')})\" if node[0] == :command\n",
    "  receiver = node[1]\n",
    "  method = node[3].is_a?(Array) ? node[3][1] : node[3].to_s\n",
    "  \"#{normalize(receiver)}.#{method}(#{args.join(', ')})\"\n",
    "end\n",
    "\n",
    "def normalize_args(node)\n",
    "  return [] unless node.is_a?(Array)\n",
    "  case node[0]\n",
    "  when :args_add_block, :arg_paren\n",
    "    normalize_args(node[1])\n",
    "  when :args_add_star\n",
    "    normalize_args(node[1])\n",
    "  when :args_new\n",
    "    []\n",
    "  else\n",
    "    node.reject { |child| child == false || child.nil? }.map { |child| normalize(child) }\n",
    "  end\n",
    "end\n",
    "\n",
    "def normalize_elements(node)\n",
    "  return [] unless node.is_a?(Array)\n",
    "  return normalize_args(node[1]) if node[0] == :args_add_block\n",
    "  node.reject { |c| c == false || c.nil? }.map { |c| normalize(c) }\n",
    "end\n",
    "\n",
    "# Assertion methods whose FIRST argument is the expectation (Ruby and Minitest\n",
    "# put the expected value first, unlike Python and Go). Swapped to the\n",
    "# subject-first form the shared engine uses.\n",
    "EXPECTED_FIRST = %w[\n",
    "  assert_equal assert_not_equal refute_equal\n",
    "  assert_same assert_not_same\n",
    "].freeze\n",
    "\n",
    "# Assertion methods whose single argument is a predicate.\n",
    "PREDICATE = %w[\n",
    "  assert refute assert_nil refute_nil assert_empty refute_empty\n",
    "  assert_includes refute_includes assert_match refute_match\n",
    "  assert_operator assert_predicate assert_kind_of assert_instance_of\n",
    "  assert_respond_to assert_send\n",
    "].freeze\n",
    "\n",
    "def assertion?(name)\n",
    "  return false unless name.is_a?(String)\n",
    "  name.start_with?(\"assert\") || name.start_with?(\"refute\") || name == \"flunk\"\n",
    "end\n",
    "\n",
    "def line_of(node)\n",
    "  return nil unless node.is_a?(Array)\n",
    "  if node[0].to_s.start_with?(\"@\") && node[2].is_a?(Array)\n",
    "    return node[2][0]\n",
    "  end\n",
    "  node.each do |child|\n",
    "    found = line_of(child)\n",
    "    return found if found\n",
    "  end\n",
    "  nil\n",
    "end\n",
    "\n",
    "# Collect def nodes anywhere in the tree, with their bodies.\n",
    "def each_method(node, &block)\n",
    "  return unless node.is_a?(Array)\n",
    "  if node[0] == :def\n",
    "    name = node[1].is_a?(Array) ? node[1][1] : node[1].to_s\n",
    "    yield name, node\n",
    "    return\n",
    "  end\n",
    "  node.each { |child| each_method(child, &block) }\n",
    "end\n",
    "\n",
    "# Walk a method body collecting calls.\n",
    "def each_node(node, &block)\n",
    "  return unless node.is_a?(Array)\n",
    "  yield node\n",
    "  node.each { |child| each_node(child, &block) }\n",
    "end\n",
    "\n",
    "def call_name(node)\n",
    "  case node[0]\n",
    "  when :command, :method_add_arg\n",
    "    inner = node[1]\n",
    "    return inner[1] if inner.is_a?(Array) && inner[0] == :@ident\n",
    "    return inner[1] if inner.is_a?(Array) && inner[0] == :fcall && inner[1].is_a?(Array)\n",
    "    if inner.is_a?(Array) && inner[0] == :call && inner[3].is_a?(Array)\n",
    "      return inner[3][1]\n",
    "    end\n",
    "    nil\n",
    "  when :command_call\n",
    "    node[3].is_a?(Array) ? node[3][1] : nil\n",
    "  else\n",
    "    nil\n",
    "  end\n",
    "end\n",
    "\n",
    "def call_args(node)\n",
    "  case node[0]\n",
    "  when :method_add_arg\n",
    "    normalize_args(node[2])\n",
    "  when :command\n",
    "    normalize_args(node[2])\n",
    "  when :command_call\n",
    "    normalize_args(node[4])\n",
    "  else\n",
    "    []\n",
    "  end\n",
    "end\n",
    "\n",
    "def leading_not(source)\n",
    "  source.to_s.start_with?(\"!\")\n",
    "end\n",
    "\n",
    "def summarize(path)\n",
    "  source = File.read(path)\n",
    "  tree = Ripper.sexp(source)\n",
    "  return { \"format\" => 1, \"error\" => \"could not parse\" } if tree.nil?\n",
    "\n",
    "  functions = []\n",
    "  each_method(tree) do |name, node|\n",
    "    next unless name.start_with?(\"test_\") || name.start_with?(\"spec_\")\n",
    "\n",
    "    assertions = []\n",
    "    bindings = {}\n",
    "    guards = []\n",
    "\n",
    "    each_node(node) do |child|\n",
    "      # Simple `v = expr` bindings, so a rebound subject is recognized.\n",
    "      if child[0] == :assign && child[1].is_a?(Array) && child[1][0] == :var_field\n",
    "        target = child[1][1]\n",
    "        if target.is_a?(Array) && target[0] == :@ident\n",
    "          var = target[1]\n",
    "          # A name assigned more than once is not resolvable, since the later\n",
    "          # value is what the assertion sees. `nil` marks it unresolvable.\n",
    "          if bindings.key?(var)\n",
    "            bindings[var] = nil\n",
    "          else\n",
    "            bindings[var] = normalize(child[2])\n",
    "          end\n",
    "        end\n",
    "      end\n",
    "\n",
    "      # `raise`/`flunk` inside a conditional is a failure guard, not an\n",
    "      # assertion, so the assertion rules would never see its removal.\n",
    "      if %i[if unless].include?(child[0])\n",
    "        body = child[2]\n",
    "        if contains_raise?(body)\n",
    "          guards << normalize(child[1])\n",
    "        end\n",
    "      end\n",
    "\n",
    "      next unless %i[command method_add_arg command_call].include?(child[0])\n",
    "      call = call_name(child)\n",
    "      next unless call && assertion?(call)\n",
    "      args = call_args(child)\n",
    "      rendered =\n",
    "        if EXPECTED_FIRST.include?(call) && args.size >= 2\n",
    "          \"#{args[1]} Eq #{args[0]}\"\n",
    "        elsif args.empty?\n",
    "          call == \"flunk\" ? \"flunk\" : call\n",
    "        else\n",
    "          args[0]\n",
    "        end\n",
    "      assertions << { \"line\" => line_of(child) || 0, \"test\" => rendered }\n",
    "    end\n",
    "\n",
    "    functions << {\n",
    "      \"name\" => name,\n",
    "      \"line\" => line_of(node) || 0,\n",
    "      \"assertions\" => assertions,\n",
    "      \"skipped\" => source.include?(\"skip\") && skips?(node),\n",
    "      \"body_is_empty\" => false,\n",
    "      \"bindings\" => bindings.compact,\n",
    "      \"guards\" => guards\n",
    "    }\n",
    "  end\n",
    "\n",
    "  { \"format\" => 1, \"functions\" => functions }\n",
    "end\n",
    "\n",
    "def contains_raise?(node)\n",
    "  return false unless node.is_a?(Array)\n",
    "  return true if %i[raise].include?(node[0])\n",
    "  if node[0] == :command && node[1].is_a?(Array)\n",
    "    return true if %w[raise flunk fail].include?(node[1][1].to_s)\n",
    "  end\n",
    "  node.any? { |child| contains_raise?(child) }\n",
    "end\n",
    "\n",
    "def skips?(node)\n",
    "  found = false\n",
    "  each_node(node) do |child|\n",
    "    if %i[command method_add_arg].include?(child[0])\n",
    "      name = call_name(child)\n",
    "      found = true if name == \"skip\"\n",
    "    end\n",
    "  end\n",
    "  found\n",
    "end\n",
    "\n",
    "begin\n",
    "  result = summarize(ARGV[0])\n",
    "rescue StandardError => error\n",
    "  result = { \"format\" => 1, \"error\" => \"#{error.class}: #{error.message}\" }\n",
    "end\n",
    "puts JSON.generate(result)\n",
    "\n",
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_tool_has_the_expected_shape() {
        assert!(SUMMARY_SCRIPT.contains("require \"ripper\""));
        assert!(SUMMARY_SCRIPT.contains("Ripper.sexp"));
        assert!(SUMMARY_SCRIPT.contains("JSON.generate"));
    }

    /// Minitest and RSpec put the expected value FIRST, unlike Python and Go.
    /// The swap is what makes the shared engine's subject-first comparison
    /// work, and getting it wrong would invert every expectation rather than
    /// fail loudly.
    #[test]
    fn the_tool_swaps_expected_first_assertions() {
        assert!(SUMMARY_SCRIPT.contains("EXPECTED_FIRST"));
        assert!(SUMMARY_SCRIPT.contains("assert_equal"));
        assert!(SUMMARY_SCRIPT.contains("args[1]"));
    }

    /// Guards are failures without an assertion macro, so the assertion rules
    /// never see their removal.
    #[test]
    fn the_tool_collects_failure_guards() {
        assert!(SUMMARY_SCRIPT.contains("contains_raise?"));
        assert!(SUMMARY_SCRIPT.contains("guards"));
    }
}
